tap "homebrew/bundle"
tap "tavianator/tap"
brew "ack"
brew "glib"
brew "harfbuzz"
brew "pango"
brew "librsvg"
brew "adwaita-icon-theme"
brew "webp"
brew "git"
brew "asdf"
brew "at-spi2-core"
brew "bash"
brew "bat"
brew "cmake"
brew "gnutls"
brew "libass"
brew "libmicrohttpd"
brew "librist"
brew "tesseract"
brew "ffmpeg"
brew "cmus"
brew "coreutils"
brew "ctags"
brew "curl"
brew "docker"
brew "gsettings-desktop-schemas"
brew "easy-tag"
brew "eza"
brew "fd"
brew "findutils"
brew "fzf"
brew "gawk"
brew "gcc"
brew "gnu-sed"
brew "gnupg"
brew "grc"
brew "grep"
brew "handbrake"
brew "htop"
brew "imagemagick"
brew "jq"
brew "lesspipe"
brew "luarocks"
brew "neovim"
brew "pandoc"
brew "pipx"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "telnet"
brew "tmux"
brew "trash-cli", link: true
brew "tree"
brew "tty-clock"
brew "wget"
brew "yarn"
brew "yt-dlp"
cask "bettertouchtool", args: { appdir: "~/Applications" }
cask "dash3", args: { appdir: "~/Applications" }
cask "notion", args: { appdir: "~/Applications" }
cask "obsidian", args: { appdir: "~/Applications" }
cask "proxyman", args: { appdir: "~/Applications" }
cask "shifty", args: { appdir: "~/Applications" }
cask "shottr", args: { appdir: "~/Applications" }
cargo "paper-terminal"
